version: 0.2

phases:
  install: 
    runtime-versions:
      php: 8.1
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      # - $(aws ecr get-login-password --no-include-email --region ${deploy_region})
      - aws ecr get-login-password --region ${deploy_region} | docker login --username AWS --password-stdin 893772890394.dkr.ecr.${deploy_region}.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo installing composer..
      - composer install
      - echo creating .env file..
      - cp .env.example .env
      - echo generating app key
      - php artisan key:generate
      - ls
      - echo Building the Docker image...          
      - docker build -t ${docker_image} .   
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push ${docker_image}
      - printf '[{"name":"${container_name}","imageUri":"${docker_image}"}]' > imagedefinitions.json

artifacts:
  # include all files required to run application
  # we include only the static build files
  files:
    - 'imagedefinitions.json'